import './legacy-core.js';import './assets/fonts.js';import './core.js';import './creative.js';import Module from './vendor/manifold.js';
const C=globalThis.FaceCore;let factory=null,backData=null;
async function bytes(url){if(globalThis.process?.versions?.node){let fs=await import('node:fs/promises');return new Uint8Array(await fs.readFile(url))}let r=await fetch(url);if(!r.ok)throw Error('Could not load local geometry asset: '+r.status);return new Uint8Array(await r.arrayBuffer())}
async function init(){if(!factory)factory=(async()=>{let wasm=await bytes(new URL('./vendor/manifold.wasm',import.meta.url)),m=await Module({wasmBinary:wasm});m.setup();return m})();return factory}
async function backing(){if(!backData)backData=JSON.parse(new TextDecoder().decode(await bytes(new URL('./assets/valve-backing.json',import.meta.url))));return backData}
function sectionForObject(o,p,M,keep){const cs=(paths,rule)=>keep(paths.length?new M.CrossSection(paths,rule):M.CrossSection.square([0,0]));let source={...o,symmetry:null},section=source.parts?.length?keep(M.CrossSection.union(source.parts.map(part=>cs(C.polygons({...source,contours:part.contours},p),part.fillRule)))):cs(C.polygons(source,p),source.type==='text'?'NonZero':source.fillRule||'EvenOdd');if(o.type==='text'&&o.textOutline>0)section=keep(keep(section.offset(o.textOutline/2,'Round')).subtract(keep(section.offset(-o.textOutline/2,'Round'))));if(o.symmetry&&o.symmetry.mode!=='none')section=cs(FaceCreative.symmetry(section.toPolygons(),o.symmetry),'NonZero');return section}
export async function build(input,options={}){
const p=C.migrate(input),M=await init(),owned=[],keep=x=>(owned.push(x),x),cs=(paths,rule='EvenOdd')=>keep(paths.length?new M.CrossSection(paths,rule):M.CrossSection.square([0,0])),union=items=>items.length?keep(M.CrossSection.union(items)):cs([]),add=(a,b)=>keep(a.add(b)),sub=(a,b)=>keep(a.subtract(b)),inter=(a,b)=>keep(a.intersect(b)),ext=(s,h,z=0)=>keep(keep(s.extrude(h)).translate([0,0,z])),mUnion=arr=>keep(M.Manifold.union(arr)),mSub=(a,b)=>keep(a.subtract(b)),mInter=(a,b)=>keep(a.intersect(b)),colors=new Map(),original=(solid,color)=>{let a=keep(solid.asOriginal());colors.set(a.originalID(),color);return a};
try{
const face=cs(C.outline(p)),protect=p.mounting!=='none'&&p.protectMounts?union(C.mounts(p).map(([x,y])=>keep(keep(M.CrossSection.square([18,18],true)).translate([x,y])))):cs([]);let cuts=[],engraves=[],artworks=[],objectPaths={},issues=[];
function objectSection(o){let shape=sectionForObject(o,p,M,keep);shape=inter(shape,face);for(let z of p.keepouts||[])shape=sub(shape,keep(keep(M.CrossSection.square([z.w,z.h],true)).translate([z.x,z.y])));if(o.op==='cut'&&o.bridges>0){let holes=shape.toPolygons().filter(q=>q.reduce((a,v,i)=>a+v[0]*q[(i+1)%q.length][1]-q[(i+1)%q.length][0]*v[1],0)<0);for(let hole of holes){let b=C.bounds([hole]),y=(b.minY+b.maxY)/2;shape=sub(shape,keep(keep(M.CrossSection.square([p.width*2,o.bridges],true)).translate([0,y])))}}if((o.op==='cut'||o.op==='engrave')&&p.protectMounts)shape=sub(shape,protect);return shape}
function imageSections(o){let levels=o.relief==='gray'?Math.round(o.levels):1,result=[];for(let n=1;n<=levels;n++){let contours=[],wanted=(x,y)=>{let v=o.pixels[y*o.iw+x],strength=o.invert?v/255:1-v/255;return o.relief==='gray'?Math.round(strength*levels)>=n:(o.invert?v>=o.threshold:v<o.threshold)};for(let y=0;y<o.ih;y++){let x=0;while(x<o.iw){while(x<o.iw&&!wanted(x,y))x++;let start=x;while(x<o.iw&&wanted(x,y))x++;if(x>start){let l=start/o.iw-.5,r=x/o.iw-.5,t=y/o.ih-.5,b=(y+1)/o.ih-.5;contours.push([[l,t],[r,t],[r,b],[l,b]])}}}if(contours.length){let shape=cs(C.polygons({...o,type:'path',contours},p),'NonZero');shape=inter(shape,face);for(let z of p.keepouts||[])shape=sub(shape,keep(keep(M.CrossSection.square([z.w,z.h],true)).translate([z.x,z.y])));if(p.protectMounts&&o.op==='engrave')shape=sub(shape,protect);result.push({section:shape,depth:o.depth*n/levels,n,levels})}}return result}
for(let o of p.objects.filter(o=>o.visible!==false)){if(o.type==='image')continue;let section=objectSection(o);objectPaths[o.id]=section.toPolygons();if(o.op==='cut')cuts.push(section);else if(o.op==='engrave')engraves.push(section);else artworks.push(section)}
let cut=union(cuts),remaining=sub(face,cut),engrave=union(engraves),art=union(artworks),laserRemaining=remaining;
if(p.kerf>0)laserRemaining=keep(remaining.offset(p.kerf/2,'Round',2,C.segments(p.kerf/2,p.precision)));
let laser={CUT:laserRemaining.toPolygons(),ENGRAVE:engrave.toPolygons(),ARTWORK:art.toPolygons()},componentSections=remaining.decompose();owned.push(...componentSections);if(componentSections.length>1)issues.push({severity:'Review',confidence:'High',text:`Front cut layout leaves ${componentSections.length} separate material pieces. Review islands and stencil bridges.`});
if(!cut.isEmpty()){let nearEdge=sub(keep(cut.offset(p.minWall,'Round')),face);if(nearEdge.area()>.001)issues.push({severity:'Review',confidence:'High',text:`A cut is within ${p.minWall} mm of the outer edge or opens the perimeter.`});let expanded=keep(cut.offset(p.minWall/2,'Round')),a=cut.decompose(),b=expanded.decompose();owned.push(...a,...b);if(b.length<a.length)issues.push({severity:'Review',confidence:'Medium',text:`Separate cut regions approach within ${p.minWall} mm; inspect the web between them.`})}
if(p.objects.some(o=>o.visible!==false&&o.type==='image')){let mask=sub(remaining,protect);for(let z of p.keepouts||[])mask=sub(mask,keep(keep(M.CrossSection.square([z.w,z.h],true)).translate([z.x,z.y])));laser.__rasterClip=mask.toPolygons()}
let geometry2D={laser,objectPaths,issues,frontArea:remaining.area(),frontPieces:componentSections.length};
if(options.only2D)return geometry2D;
let base;if(p.bevel>0){let lower=ext(face,p.thickness-p.bevel),cap=keep(face.offset(-p.bevel,'Round')),thin1=ext(face,.001,p.thickness-p.bevel-.001),thin2=ext(cap,.001,p.thickness-.001),bevel=keep(M.Manifold.hull([thin1,thin2]));base=mUnion([lower,bevel])}else base=ext(face,p.thickness);
if(p.mounting==='cad'){let data=await backing(),mesh=new M.Mesh({numProp:3,vertProperties:new Float32Array(data.positions),triVerts:new Uint32Array(data.triangles),tolerance:.0001});mesh.merge();let back=keep(M.Manifold.ofMesh(mesh));if(back.status()!=='NoError')throw Error('CAD backing mesh failed its topology check: '+back.status());base=mUnion([back,base,ext(face,.031,-.03)])}
if(p.mounting==='round'){let pockets=union(C.mounts(p).map(([x,y])=>keep(keep(M.CrossSection.circle(p.magnetDiameter/2,C.segments(p.magnetDiameter/2,p.precision))).translate([x,y]))));base=mSub(base,ext(pockets,p.magnetDepth+.01,-.01))}
base=original(base,p.color);let model=base,raisedParts=[],cutSolid=cut.isEmpty()?null:original(ext(cut,60,-30),p.color);
for(let o of p.objects.filter(o=>o.visible!==false&&o.op!=='cut')){let chunks=o.type==='image'?imageSections(o).map(v=>({section:v.section,depth:v.depth})): [{section:objectSection(o),depth:o.depth}];for(let v of chunks){if(v.section.isEmpty())continue;if(o.op==='raise'){let solid=original(ext(v.section,v.depth+.005,p.thickness-.005),o.color);raisedParts.push({id:o.id,name:o.name,color:o.color,solid});model=mUnion([model,solid])}else model=mSub(model,original(ext(v.section,v.depth+.01,p.thickness-v.depth),p.color))}}
if(cutSolid)model=mSub(model,cutSolid);
function meshData(s){if(s.isEmpty())throw Error('The design contains no remaining printable material.');let status=s.status();if(status!=='NoError')throw Error('Solid geometry failed: '+status);let mesh=s.getMesh();if(mesh.triVerts.length>3000000)throw Error('Model exceeds one million triangles. Reduce pattern density or image levels.');let stride=mesh.numProp,triColor=new Uint16Array(mesh.triVerts.length/3),palette=[p.color],addColor=c=>{let i=palette.indexOf(c);if(i<0){i=palette.length;palette.push(c)}return i};for(let i=0;i<mesh.runOriginalID.length;i++){let color=addColor(colors.get(mesh.runOriginalID[i])||p.color);triColor.fill(color,mesh.runIndex[i]/3,mesh.runIndex[i+1]/3)}let parts=s.decompose();owned.push(...parts);return {positions:new Float32Array(mesh.vertProperties),triangles:new Uint32Array(mesh.triVerts),stride,triColor,palette,volume:s.volume(),bounds:s.boundingBox(),surfaceArea:s.surfaceArea(),components:parts.length,trianglesCount:mesh.triVerts.length/3,status}}
if(options.coupons){let out=[];for(let [i,[x,y]]of C.mounts(p).entries()){let box=keep(keep(M.Manifold.cube([24,24,30],true)).translate([x,y,0])),piece=mInter(model,box);if(!piece.isEmpty())out.push({name:'mount-coupon-'+(i+1),mesh:meshData(piece)})}return {...geometry2D,coupons:out}}
if(options.insets){let parts=[];for(let o of p.objects.filter(o=>o.visible!==false&&o.inlay&&o.op==='engrave'&&o.type!=='image')){let s=objectSection(o),clearance=options.clearance??.15,shrink=keep(s.offset(-clearance,'Round'));if(!shrink.isEmpty())parts.push({name:o.name,z:p.thickness-o.depth,mesh:meshData(original(ext(shrink,o.depth),o.color))})}return {...geometry2D,insets:parts}}
let mesh=meshData(model);if(mesh.components>1)issues.push({severity:'Review',confidence:'High',text:`The printed model contains ${mesh.components} disconnected solids. Review loose islands before slicing.`});return {...geometry2D,mesh};
}finally{for(let obj of owned.reverse())try{obj.delete()}catch{}}
}
export async function laserStack(input){const p=C.migrate(input),M=await init(),owned=[],keep=x=>(owned.push(x),x),cs=q=>keep(new M.CrossSection(q,'EvenOdd'));try{let face=cs(C.outline(p)),inner=keep(face.offset(-8,'Round')),ring=keep(face.subtract(inner)),pads=keep(M.CrossSection.union(C.mounts(p).map(([x,y])=>keep(keep(M.CrossSection.circle(9,96)).translate([x,y]))))),frame=keep(keep(ring.add(pads)).intersect(face));let holes=diam=>keep(M.CrossSection.union(C.mounts(p).map(([x,y])=>keep(keep(M.CrossSection.circle(diam/2,64)).translate([x,y])))));let compensate=s=>p.kerf?keep(s.offset(p.kerf/2,'Round')):s,spacer=keep(frame.subtract(holes(p.magnetDiameter))),retainer=keep(frame.subtract(holes(Math.max(2,p.magnetDiameter-1.4))));let guide=holes(p.alignmentHole).toPolygons();return {spacer:{CUT:compensate(spacer).toPolygons(),ALIGN_GUIDE:guide},retainer:{CUT:compensate(retainer).toPolygons(),ALIGN_GUIDE:guide},notes:'Prototype laminated carrier: spacer holes receive magnets; smaller retainer openings retain them. Verify magnet thickness, contact depth, assembly registration and airflow.'}}finally{for(let o of owned.reverse())try{o.delete()}catch{}}}

// Vector editing shares the same solid-kernel contours as manufacturing.
export async function vectorEdit(input,options={}){let p=C.migrate(input),M=await init(),owned=[],keep=x=>(owned.push(x),x),cs=(paths,rule='NonZero')=>keep(paths.length?new M.CrossSection(paths,rule):M.CrossSection.square([0,0]));try{let objects=p.objects.filter(o=>(options.ids||[]).includes(o.id));if(!objects.length)throw Error('Select a source shape.');let shape;if(options.operation==='trace'){let o=objects[0];if(o.type!=='image')throw Error('Select an imported image.');let q=FaceCreative.cleanPixels(o,options.threshold??128,options.speckle??3,!!options.invert);let path={...o,type:'path',contours:q};shape=cs(C.polygons(path,p));if(options.simplify>0)shape=keep(shape.simplify(options.simplify));}else{let sections=objects.map(o=>{if(o.type==='image')throw Error('Trace images before combining.');return sectionForObject(o,p,M,keep)});shape=sections[0];for(let next of sections.slice(1))shape=keep(options.operation==='subtract'?shape.subtract(next):options.operation==='intersect'?shape.intersect(next):shape.add(next));let offset=Number(options.offset||0);if(!Number.isFinite(offset)||Math.abs(offset)>20)throw Error('Offset must be −20 to 20 mm.');if(options.operation==='border'){if(offset<=0)throw Error('Border width must be positive.');shape=keep(keep(shape.offset(offset/2,'Round')).subtract(keep(shape.offset(-offset/2,'Round'))))}else if(offset)shape=keep(shape.offset(offset,'Round'));}if(shape.isEmpty())throw Error('This operation leaves no shape. Adjust the selection or settings.');return {contours:shape.toPolygons(),area:shape.area()}}finally{for(let s of owned.reverse())try{s.delete()}catch{}}}

export async function materialStack(input,options={}){let p=C.migrate(input);if(!p.stack?.length)throw Error('Add at least one material sheet.');let parts=[],z=0;for(let [index,sheet]of p.stack.entries()){let q=C.clone(p);q.stack=[];q.keepouts=p.keepouts||[];q.mounting='none';q.thickness=sheet.thickness;q.bevel=0;q.color=sheet.color;q.material=sheet.material||'Sheet';q.objects=p.objects.filter(o=>sheet.layers.includes(o.id)).map(o=>({...C.clone(o),symmetry:o.symmetry,depth:Math.min(o.depth,sheet.thickness-.1)}));if(sheet.hole>0)for(let [i,[x,y]]of [[-1,-1],[1,-1],[1,1],[-1,1]].entries()){let r=sheet.hole/2+4;q.objects.push({id:'registration-'+i,name:'Registration '+(i+1),type:'circle',x:x*(q.width/2-r),y:y*(q.height/2-r),w:sheet.hole,h:sheet.hole,rotation:0,op:'cut',depth:1,color:sheet.color,corner:0,bridges:0})}let result=await build(q,options.only2D?{only2D:true}:{});if(index>0)z-=sheet.thickness+(options.explode??0);parts.push({name:sheet.name,material:sheet.material,project:q,z,result})}return {parts,totalThickness:p.stack.reduce((n,s)=>n+s.thickness,0)}}

export async function calibration(input,options={}){const p=C.migrate(input),kind=options.kind||'clearance',start=Number(options.start??.1),step=Number(options.step??.05);if(!['clearance','kerf','relief'].includes(kind)||!Number.isFinite(start)||!Number.isFinite(step)||step<=0||start<0||start+step*4>(kind==='relief'?5:kind==='clearance'?.5:1))throw Error('Choose a valid five-step calibration range.');let q=C.defaults();q.width=120;q.height=50;q.thickness=3;q.name=kind+' calibration';q.color=p.color;q.objects=[];let values=[];for(let i=0;i<5;i++){let value=Number((start+i*step).toFixed(3)),x=-44+i*22;values.push(value);let base={id:'feature'+i,name:String(value)+' mm',type:'rect',x,y:0,w:14,h:14,rotation:0,op:kind==='relief'?'raise':'engrave',depth:kind==='relief'?Math.max(.01,value):1.5,color:'#cfed75',corner:0,bridges:0,inlay:kind==='clearance'};if(kind==='kerf'){base.op='cut';base.w=base.h=10-value}else if(kind==='clearance'){base.w=base.h=14+2*value}q.objects.push(base,{...base,id:'label'+i,name:'Label '+value,type:'text',font:'mono',text:String(value),y:17,w:15,h:4,op:'engrave',depth:.4,inlay:false});}let result=await build(q),plugs=[];if(kind==='clearance'){for(let i=0;i<5;i++){let plug=C.defaults();plug.width=20;plug.height=20;plug.thickness=1.5;plug.radius=0;plug.objects=[{id:'trim',name:'Outside plug',type:'path',x:0,y:0,w:20,h:20,contours:[C.roundedRect(20,20,0).map(([x,y])=>[x/20,y/20]),C.roundedRect(14,14,0).map(([x,y])=>[x/20,y/20])],fillRule:'EvenOdd',rotation:0,op:'cut',depth:1,color:'#cfed75',corner:0,bridges:0}];plugs.push({name:'plug-'+(i+1),mesh:(await build(plug)).mesh})}}return {project:q,result,values,kind,plugs}}
