import './legacy-core.js';import './assets/fonts.js';import './core.js';import Module from './vendor/manifold.js';
const C=globalThis.FaceCore;let factory=null,backData=null;
async function bytes(url){if(globalThis.process?.versions?.node){let fs=await import('node:fs/promises');return new Uint8Array(await fs.readFile(url))}let r=await fetch(url);if(!r.ok)throw Error('Could not load local geometry asset: '+r.status);return new Uint8Array(await r.arrayBuffer())}
async function init(){if(!factory)factory=(async()=>{let wasm=await bytes(new URL('./vendor/manifold.wasm',import.meta.url)),m=await Module({wasmBinary:wasm});m.setup();return m})();return factory}
async function backing(){if(!backData)backData=JSON.parse(new TextDecoder().decode(await bytes(new URL('./assets/valve-backing.json',import.meta.url))));return backData}
export async function build(input,options={}){
const p=C.migrate(input),M=await init(),owned=[],keep=x=>(owned.push(x),x),cs=(paths,rule='EvenOdd')=>keep(paths.length?new M.CrossSection(paths,rule):M.CrossSection.square([0,0])),union=items=>items.length?keep(M.CrossSection.union(items)):cs([]),add=(a,b)=>keep(a.add(b)),sub=(a,b)=>keep(a.subtract(b)),inter=(a,b)=>keep(a.intersect(b)),ext=(s,h,z=0)=>keep(keep(s.extrude(h)).translate([0,0,z])),mUnion=arr=>keep(M.Manifold.union(arr)),mSub=(a,b)=>keep(a.subtract(b)),mInter=(a,b)=>keep(a.intersect(b)),colors=new Map(),original=(solid,color)=>{let a=keep(solid.asOriginal());colors.set(a.originalID(),color);return a};
try{
const face=cs(C.outline(p)),protect=p.mounting!=='none'&&p.protectMounts?union(C.mounts(p).map(([x,y])=>keep(keep(M.CrossSection.square([18,18],true)).translate([x,y])))):cs([]);let cuts=[],engraves=[],artworks=[],objectPaths={},issues=[];
function objectSection(o){let shape;if(o.type==='path'&&o.parts?.length){shape=union(o.parts.map(part=>{let n={...o,contours:part.contours};return cs(C.polygons(n,p),part.fillRule||'EvenOdd')}))}else shape=cs(C.polygons(o,p),o.type==='text'?'NonZero':o.fillRule||'EvenOdd');shape=inter(shape,face);if(o.op==='cut'&&o.bridges>0){let holes=shape.toPolygons().filter(q=>q.reduce((a,v,i)=>a+v[0]*q[(i+1)%q.length][1]-q[(i+1)%q.length][0]*v[1],0)<0);for(let hole of holes){let b=C.bounds([hole]),y=(b.minY+b.maxY)/2;shape=sub(shape,keep(keep(M.CrossSection.square([p.width*2,o.bridges],true)).translate([0,y])))}}if((o.op==='cut'||o.op==='engrave')&&p.protectMounts)shape=sub(shape,protect);return shape}
function imageSections(o){let levels=o.relief==='gray'?Math.round(o.levels):1,result=[];for(let n=1;n<=levels;n++){let contours=[],wanted=(x,y)=>{let v=o.pixels[y*o.iw+x],strength=o.invert?v/255:1-v/255;return o.relief==='gray'?Math.round(strength*levels)>=n:(o.invert?v>=o.threshold:v<o.threshold)};for(let y=0;y<o.ih;y++){let x=0;while(x<o.iw){while(x<o.iw&&!wanted(x,y))x++;let start=x;while(x<o.iw&&wanted(x,y))x++;if(x>start){let l=start/o.iw-.5,r=x/o.iw-.5,t=y/o.ih-.5,b=(y+1)/o.ih-.5;contours.push([[l,t],[r,t],[r,b],[l,b]])}}}if(contours.length){let shape=cs(C.polygons({...o,type:'path',contours},p),'NonZero');shape=inter(shape,face);if(p.protectMounts&&o.op==='engrave')shape=sub(shape,protect);result.push({section:shape,depth:o.depth*n/levels,n,levels})}}return result}
for(let o of p.objects.filter(o=>o.visible!==false)){if(o.type==='image')continue;let section=objectSection(o);objectPaths[o.id]=section.toPolygons();if(o.op==='cut')cuts.push(section);else if(o.op==='engrave')engraves.push(section);else artworks.push(section)}
let cut=union(cuts),remaining=sub(face,cut),engrave=union(engraves),art=union(artworks),laserRemaining=remaining;
if(p.kerf>0)laserRemaining=keep(remaining.offset(p.kerf/2,'Round',2,C.segments(p.kerf/2,p.precision)));
let laser={CUT:laserRemaining.toPolygons(),ENGRAVE:engrave.toPolygons(),ARTWORK:art.toPolygons()},componentSections=remaining.decompose();owned.push(...componentSections);if(componentSections.length>1)issues.push({severity:'Review',confidence:'High',text:`Front cut layout leaves ${componentSections.length} separate material pieces. Review islands and stencil bridges.`});
if(!cut.isEmpty()){let nearEdge=sub(keep(cut.offset(p.minWall,'Round')),face);if(nearEdge.area()>.001)issues.push({severity:'Review',confidence:'High',text:`A cut is within ${p.minWall} mm of the outer edge or opens the perimeter.`});let expanded=keep(cut.offset(p.minWall/2,'Round')),a=cut.decompose(),b=expanded.decompose();owned.push(...a,...b);if(b.length<a.length)issues.push({severity:'Review',confidence:'Medium',text:`Separate cut regions approach within ${p.minWall} mm; inspect the web between them.`})}
let geometry2D={laser,objectPaths,issues,frontArea:remaining.area(),frontPieces:componentSections.length};
if(options.only2D)return geometry2D;
let base;if(p.bevel>0){let lower=ext(face,p.thickness-p.bevel),cap=keep(face.offset(-p.bevel,'Round')),thin1=ext(face,.001,p.thickness-p.bevel-.001),thin2=ext(cap,.001,p.thickness-.001),bevel=keep(M.Manifold.hull([thin1,thin2]));base=mUnion([lower,bevel])}else base=ext(face,p.thickness);
if(p.mounting==='cad'){let data=await backing(),mesh=new M.Mesh({numProp:3,vertProperties:new Float32Array(data.positions),triVerts:new Uint32Array(data.triangles),tolerance:.0001});mesh.merge();let back=keep(M.Manifold.ofMesh(mesh));if(back.status()!=='NoError')throw Error('CAD backing mesh failed its topology check: '+back.status());base=mUnion([back,base,ext(face,.031,-.03)])}
if(p.mounting==='round'){let pockets=union(C.mounts(p).map(([x,y])=>keep(keep(M.CrossSection.circle(p.magnetDiameter/2,C.segments(p.magnetDiameter/2,p.precision))).translate([x,y]))));base=mSub(base,ext(pockets,p.magnetDepth+.01,-.01))}
base=original(base,p.color);let model=base,raisedParts=[],cutSolid=cut.isEmpty()?null:original(ext(cut,60,-30),p.color);
for(let o of p.objects.filter(o=>o.visible!==false&&o.op!=='cut')){let chunks=o.type==='image'?imageSections(o).map(v=>({section:v.section,depth:v.depth})): [{section:objectSection(o),depth:o.depth}];for(let v of chunks){if(v.section.isEmpty())continue;if(o.op==='raise'){let solid=original(ext(v.section,v.depth+.005,p.thickness-.005),o.color);raisedParts.push({id:o.id,name:o.name,color:o.color,solid});model=mUnion([model,solid])}else model=mSub(model,original(ext(v.section,v.depth+.01,p.thickness-v.depth),p.color))}}
if(cutSolid)model=mSub(model,cutSolid);
function meshData(s){if(s.isEmpty())throw Error('The design contains no remaining printable material.');let status=s.status();if(status!=='NoError')throw Error('Solid geometry failed: '+status);let mesh=s.getMesh(),stride=mesh.numProp,triColor=new Uint16Array(mesh.triVerts.length/3),palette=[p.color],addColor=c=>{let i=palette.indexOf(c);if(i<0){i=palette.length;palette.push(c)}return i};for(let i=0;i<mesh.runOriginalID.length;i++){let color=addColor(colors.get(mesh.runOriginalID[i])||p.color);triColor.fill(color,mesh.runIndex[i]/3,mesh.runIndex[i+1]/3)}let parts=s.decompose();owned.push(...parts);return {positions:new Float32Array(mesh.vertProperties),triangles:new Uint32Array(mesh.triVerts),stride,triColor,palette,volume:s.volume(),bounds:s.boundingBox(),surfaceArea:s.surfaceArea(),components:parts.length,trianglesCount:mesh.triVerts.length/3,status}}
if(options.coupons){let out=[];for(let [i,[x,y]]of C.mounts(p).entries()){let box=keep(keep(M.Manifold.cube([24,24,30],true)).translate([x,y,0])),piece=mInter(model,box);if(!piece.isEmpty())out.push({name:'mount-coupon-'+(i+1),mesh:meshData(piece)})}return {...geometry2D,coupons:out}}
if(options.insets){let parts=[];for(let o of p.objects.filter(o=>o.visible!==false&&o.inlay&&o.op==='engrave'&&o.type!=='image')){let s=objectSection(o),clearance=options.clearance??.15,shrink=keep(s.offset(-clearance,'Round'));if(!shrink.isEmpty())parts.push({name:o.name,z:p.thickness-o.depth,mesh:meshData(original(ext(shrink,o.depth),o.color))})}return {...geometry2D,insets:parts}}
let mesh=meshData(model);if(mesh.components>1)issues.push({severity:'Review',confidence:'High',text:`The printed model contains ${mesh.components} disconnected solids. Review loose islands before slicing.`});return {...geometry2D,mesh};
}finally{for(let obj of owned.reverse())try{obj.delete()}catch{}}
}
export async function laserStack(input){const p=C.migrate(input),M=await init(),owned=[],keep=x=>(owned.push(x),x),cs=q=>keep(new M.CrossSection(q,'EvenOdd'));try{let face=cs(C.outline(p)),inner=keep(face.offset(-8,'Round')),ring=keep(face.subtract(inner)),pads=keep(M.CrossSection.union(C.mounts(p).map(([x,y])=>keep(keep(M.CrossSection.circle(9,96)).translate([x,y]))))),frame=keep(keep(ring.add(pads)).intersect(face));let holes=diam=>keep(M.CrossSection.union(C.mounts(p).map(([x,y])=>keep(keep(M.CrossSection.circle(diam/2,64)).translate([x,y])))));let compensate=s=>p.kerf?keep(s.offset(p.kerf/2,'Round')):s,spacer=keep(frame.subtract(holes(p.magnetDiameter))),retainer=keep(frame.subtract(holes(Math.max(2,p.magnetDiameter-1.4))));let guide=holes(p.alignmentHole).toPolygons();return {spacer:{CUT:compensate(spacer).toPolygons(),ALIGN_GUIDE:guide},retainer:{CUT:compensate(retainer).toPolygons(),ALIGN_GUIDE:guide},notes:'Prototype laminated carrier: spacer holes receive magnets; smaller retainer openings retain them. Verify magnet thickness, contact depth, assembly registration and airflow.'}}finally{for(let o of owned.reverse())try{o.delete()}catch{}}}
