/* FACEBENCH 2.1 — focused workspace behavior. GPL-3.0-or-later. */
'use strict';
let welcomeDismissed=false,exportBusy=false,lastDialogTrigger=null;
function openPanelDialog(id,trigger){let dialog=$(id);if(!dialog)return;lastDialogTrigger=trigger||document.activeElement;dialog.querySelector('.dialogStatus').textContent='';syncWorkspace();if(!dialog.open)dialog.showModal();dialog.querySelector('[data-close]').focus()}
for(let button of document.querySelectorAll('[data-dialog]'))button.addEventListener('click',()=>openPanelDialog(button.dataset.dialog,button));
for(let dialog of document.querySelectorAll('dialog')){dialog.querySelector('[data-close]').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{lastDialogTrigger?.focus();draw()});dialog.addEventListener('click',e=>{if(e.target!==dialog)return;let r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()})}
function interaction(mode){drawing=mode==='draw';panMode=mode==='pan';spacePan=false;canvas.style.cursor=drawing?'crosshair':panMode?'grab':'default';$('drawTool').setAttribute('aria-pressed',drawing);$('pan').setAttribute('aria-pressed',panMode);$('selectTool').setAttribute('aria-pressed',!drawing&&!panMode);document.querySelector('.drawControl').hidden=!drawing;$('modeHint').textContent=drawing?'Draw on the face · Esc to select':panMode?'Drag to pan · Esc to select':'Click to select · drag to move'}
$('selectTool').onclick=()=>{interaction('select');setView('design');canvas.focus();say('Select a decoration on the face or in Layers.')};$('pan').onclick=()=>{interaction(panMode?'select':'pan');setView('design');canvas.focus()};$('drawTool').onclick=()=>{let next=drawing?'select':'draw';interaction(next);welcomeDismissed=true;prefs.left=false;applyPrefs();setView('design');syncWorkspace();canvas.focus();say(next==='draw'?'Draw a stroke on the face. Adjust its width in Create.':'Select mode restored.')};
$('welcomeText').onclick=()=>{welcomeDismissed=true;add('text');$('oText').focus();$('oText').select()};$('welcomeSample').onclick=()=>{welcomeDismissed=true;$('sample').click()};$('welcomeDismiss').onclick=()=>{welcomeDismissed=true;syncWorkspace();canvas.focus()};
for(let button of document.querySelectorAll('[data-swatch]'))button.onclick=()=>{if(!objects().some(o=>!o.locked))return;edit(()=>{for(let o of objects().filter(o=>!o.locked))o.color=button.dataset.swatch});say('Color applied to selected unlocked layers.')};
function syncWorkspace(){let os=objects(),editable=os.filter(o=>!o.locked),many=os.length>1,selectedObject=object();$('selectionHeading').textContent=os.length?(many?os.length+' layers selected':selectedObject.name):'Inspector';$('selectionHint').textContent=many?'Position, color, operation, depth and rotation apply to all unlocked selections. Select one layer to edit its size or content.':selectedObject?.locked?'This layer is locked. Unlock it in Layers to edit.':'';$('welcome').hidden=welcomeDismissed||p.objects.length>0||view!=='design';$('pocketFields').hidden=p.mounting!=='round';$('protectMounts').closest('label').hidden=p.mounting==='none';syncArrangement();$('group').disabled=editable.length<2;$('ungroup').disabled=!editable.some(o=>o.group);$('duplicate').disabled=!os.length;$('delete').disabled=!editable.length;for(let id of ['oName','oText','oFont','oW','oH','aspectLock','oCorner','oInlay','oRelief','oLevels','oThreshold','oInvert','fontImport'])$(id).disabled=many||!editable.length;for(let id of ['oX','oY','oRotation','oColor','oOp','oDepth','oBridges'])$(id).disabled=!editable.length||id==='oDepth'&&os.every(o=>o.op==='cut');$('oOp').querySelector('[value=cut]').disabled=os.some(o=>o.type==='image');for(let b of document.querySelectorAll('[data-swatch]')){b.disabled=!editable.length;b.setAttribute('aria-pressed',!!os.length&&os.every(o=>o.color.toLowerCase()===b.dataset.swatch))}$('toggleLeft').setAttribute('aria-expanded',!prefs.left);$('toggleRight').setAttribute('aria-expanded',!prefs.right);$('mode').setAttribute('aria-pressed',prefs.advanced);if($('advancedSetting'))$('advancedSetting').checked=prefs.advanced;$('selectTool').setAttribute('aria-pressed',!drawing&&!panMode);$('exportSummary').textContent=p.objects.length+' layer'+(p.objects.length===1?'':'s')+' · '+p.width+' × '+p.height+' mm';let noLayers=!p.objects.length,noMatch=!$('layers').children.length;if(noMatch){let msg=document.createElement('p');msg.className='hint';msg.textContent=noLayers?'Your decorations will appear here.':'No matching layers. Try a different name.';$('layers').append(msg)}if(exportBusy)for(let b of document.querySelectorAll('[data-export]'))b.disabled=true;}
document.addEventListener('facebench:render',syncWorkspace);document.addEventListener('facebench:status',e=>{let dialog=document.querySelector('dialog[open]');if(dialog)dialog.querySelector('.dialogStatus').textContent=e.detail;if(dialog?.id==='projectDialog'&&/^(Example loaded|Fresh blank ready|Project imported|Baseline restored)/.test(e.detail))dialog.close()});document.addEventListener('facebench:findings',e=>{let review=e.detail.filter(f=>f.severity==='Review').length;$('findingCount').textContent='· '+e.detail.length;$('checkSummary').textContent=review?review+' item'+(review===1?'':'s')+' to review. Expand the findings before fabrication.':'No additional geometry warnings. Physical fit still needs a coupon test.'});document.addEventListener('facebench:export',e=>{exportBusy=e.detail;for(let b of document.querySelectorAll('[data-export]'))b.disabled=exportBusy;if(exportBusy){let dialog=document.querySelector('dialog[open]');if(dialog)dialog.querySelector('.dialogStatus').textContent='Preparing files… You can continue when the download is ready.'}});document.addEventListener('facebench:view',e=>{for(let id of ['selectTool','pan'])$(id).hidden=e.detail!=='design';$('welcome').hidden=welcomeDismissed||p.objects.length>0||e.detail!=='design';$('modeHint').textContent=e.detail==='design'?'Click to select · drag to move':'Drag to orbit · scroll to zoom'});
for(let id of ['mode','toggleLeft','toggleRight'])$(id).addEventListener('click',syncWorkspace);$('layerSearch').addEventListener('input',syncWorkspace);
let advancedLabel=document.createElement('label');advancedLabel.className='check';advancedLabel.innerHTML='<input id="advancedSetting" type="checkbox"> Advanced controls';$('settingsDialog').querySelector('.dialogBody').prepend(advancedLabel);$('advancedSetting').onchange=()=>{prefs.advanced=$('advancedSetting').checked;applyPrefs();savePrefs();syncWorkspace()};
document.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]')||!['BODY','CANVAS'].includes(document.activeElement.tagName))return;let key=e.key.toLowerCase();if(e.key==='Escape'){interaction('select');return}if((e.metaKey||e.ctrlKey)&&key==='d'){e.preventDefault();duplicate();return}if((e.metaKey||e.ctrlKey)&&key==='a'&&document.activeElement===canvas){e.preventDefault();selected=p.objects.filter(o=>o.visible!==false).map(o=>o.id);render();return}if(e.metaKey||e.ctrlKey||e.altKey)return;let type={t:'text',r:'rect',e:'circle',s:'star'}[key];if(type){e.preventDefault();welcomeDismissed=true;add(type);return}if(key==='v')$('selectTool').click();if(key==='d')$('drawTool').click();if(key==='f')$('fit').click()});
window.addEventListener('blur',()=>{spacePan=false;canvas.style.cursor=drawing?'crosshair':panMode?'grab':'default'});
// Keep dialog shortcuts reachable without making the first screen a manual.
let shortcut=document.createElement('p');shortcut.className='hint';shortcut.textContent='Canvas shortcuts: T text · R rectangle · E ellipse · S star · D draw · V select · F fit · Ctrl/Cmd+D duplicate · Ctrl/Cmd+A select all · Ctrl/Cmd+S save JSON.';$('settingsDialog').querySelector('.dialogBody').append(shortcut);
