import assert from 'node:assert/strict';import fs from 'node:fs';import {build,vectorEdit,materialStack,calibration} from '../engine.js';const C=globalThis.FaceCore,K=globalThis.FaceCreative;let p=C.defaults();p.thickness=3;
assert.equal(C.migrate({...p,schema:2}).schema,3);assert.equal(C.migrate(globalThis.FaceLegacy.defaults()).schema,3);
for(let style of ['waves','honeycomb','contours','maze','halftone','vents']){let recipe={kind:'pattern',style,spacing:18,line:2,amplitude:4,margin:8,seed:'test'},o=K.patternObject(recipe,100,80);p.objects=[o];let before=JSON.stringify(C.polygons(o,p));assert.equal(before,JSON.stringify(C.polygons(C.migrate(JSON.parse(JSON.stringify(p))).objects[0],p)));let r=await build(p);assert.equal(r.mesh.status,'NoError');assert.equal(r.mesh.components,1);console.log('Pattern',style,r.mesh.trianglesCount);}
p.objects=[K.makePath([K.rect(30,10,10,8)],{name:'sym',op:'cut'})];let a=await build(p,{only2D:true});p.objects[0].symmetry={mode:'mirrorX',x:0,y:0,count:4};let b=await build(p,{only2D:true});assert(Math.abs((p.width*p.height-b.frontArea)-2*(p.width*p.height-a.frontArea))<.02);assert(C.inside(-30,10,p.objects[0],p));p.objects[0].symmetry.mode='radial';b=await build(p);assert.equal(b.mesh.status,'NoError');assert.equal(b.frontPieces,1);
let changed=K.remix(p,'seed',{layout:true,colors:true,text:true,patterns:true});assert.deepEqual(changed.objects,p.objects);assert.deepEqual(K.remix(p,'abc'),K.remix(p,'abc'));
p.objects=[K.makePath([K.rect(0,0,20,20)],{id:'a'}),K.makePath([K.rect(10,0,20,20)],{id:'b'})];for(let [operation,expected]of [['union',600],['subtract',200],['intersect',200]]){let r=await vectorEdit(p,{ids:['a','b'],operation});assert(Math.abs(r.area-expected)<.01)}assert((await vectorEdit(p,{ids:['a'],operation:'border',offset:2})).area>0);
let mirror={...p.objects[0],type:'rect',symmetry:{mode:'both',x:0,y:0,count:4}};p.objects=[mirror];assert(Math.abs((await vectorEdit(p,{ids:['a'],operation:'union'})).area-400)<.01,'Overlapping linked copies must union, not cancel');
let ring=K.makePath([K.rect(0,0,20,20),K.rect(0,0,10,10)],{fillRule:'EvenOdd',symmetry:{mode:'mirrorX',x:0,y:0,count:4}});p.objects=[ring];assert(Math.abs((await vectorEdit(p,{ids:[ring.id],operation:'union'})).area-300)<.01,'Symmetry preserves EvenOdd holes');assert(!C.inside(0,0,ring,p));

let img={...K.makePath([K.rect(0,0,20,20)]),type:'image',iw:4,ih:4,pixels:[0,0,255,255,0,0,255,255,255,255,255,255,255,255,255,0],data:'data:image/png;base64,AA==',threshold:128,levels:4,relief:'threshold'};p.objects=[img];let trace=await vectorEdit(p,{ids:[img.id],operation:'trace',threshold:128,speckle:2,simplify:0});assert(Math.abs(trace.area-100)<.01);p.keepouts=[{x:0,y:0,w:10,h:10}];let raster=await build(p,{only2D:true}),svg=C.formatSVG(p,raster.laser);assert(svg.includes('clipPath')&&svg.includes('clip-path="url(#facebench-raster-clip)"'));assert(!C.formatDXF(p,raster.laser).includes('__rasterClip'));p.keepouts=[];

let text={...K.makePath([K.rect(0,0,100,20)]),type:'text',font:'sans',text:'MAKE',w:100,h:20,textCurve:{mode:'arc',amount:120}};for(let mode of ['arc','ring','wave','path']){text.textCurve={mode,amount:mode==='wave'?5:120,path:[[-40,0],[0,-15],[40,0]]};p.objects=[text];let r=await build(p);assert.equal(r.mesh.status,'NoError');assert.equal(r.mesh.components,1)}
text.textCurve={mode:'arc',amount:0};text.textOutline=1;p.objects=[text];let outline=await build(p,{only2D:true}),outlineVector=await vectorEdit(p,{ids:[text.id],operation:'union'});assert(outlineVector.area>0);let flat=K.makePath(outlineVector.contours,{id:text.id});p.objects=[flat];let flattened=await build(p,{only2D:true});assert.deepEqual(flattened.laser.ARTWORK,outline.laser.ARTWORK,'Text outline is retained when converted');
let recipe={kind:'texture',style:'studs',size:4,spacing:6,width:100,height:80,strokes:[[[-25,0],[25,0]]],seed:'fixed'},paths=K.texture(recipe,100,80),tex=K.makePath(paths,{x:0,y:0,w:100,h:80,recipe,depth:2});p.objects=[tex];let relief=await build(p);assert.equal(relief.mesh.bounds.max[2],5);assert.equal(relief.mesh.components,1);p.keepouts=[{x:0,y:0,w:120,h:90}];let protectedMesh=await build(p);assert(Math.abs(protectedMesh.mesh.volume-p.width*p.height*3)<.1);p.keepouts=[];
p.stack=[{name:'Front',material:'PLA',thickness:3,color:'#eeeeee',hole:2,layers:[tex.id]},{name:'Diffuser',material:'Acrylic',thickness:2,color:'#ccddff',hole:2,layers:[]}];let stack=await materialStack(p);assert.equal(stack.parts.length,2);assert.equal(stack.parts[1].z,-2);assert.equal(stack.totalThickness,5);let exploded=await materialStack(p,{explode:10});assert.equal(exploded.parts[1].z,-12);
await assert.rejects(calibration(p,{kind:'clearance',start:.4,step:.1}),/valid five-step/);
for(let kind of ['clearance','kerf','relief']){let c=await calibration(p,{kind,start:.1,step:.05});assert.equal(c.result.mesh.status,'NoError');assert.equal(c.values.length,5);if(kind==='clearance'){assert.equal(c.plugs.length,5);assert(Math.abs(c.plugs[0].mesh.volume-14*14*1.5)<.02)}}
let stored=C.migrate(JSON.parse(JSON.stringify(p)));assert.deepEqual(stored.stack,p.stack);assert.throws(()=>C.migrate({...p,stamps:[{name:'Broken',width:100,height:80,objects:[{}]}]}));
fs.writeFileSync('/tmp/facebench-v3-sheet.stl',Buffer.from(C.stl(stack.parts[1].result.mesh)));
fs.writeFileSync('/tmp/facebench-v3-relief.stl',Buffer.from(C.stl(relief.mesh)));console.log('PASS creative geometry: migration, editable/deterministic patterns, linked symmetry, Remix locks, Boolean areas, clean tracing, curved text, brush relief, keep-outs, physical stacks and calibration.');
